import './globals.css';
import { Poppins } from 'next/font/google';
import NavBar from 'src/components/NavBar';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  styles: ['normal'],
  subsets: ['latin-ext'],
  display: 'swap',
});

export const metadata = {
  title: 'Crud-NextsJS',
  description: 'Generated by Alexander',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
