import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins9({
  weight: ['300', '400', '500', '600', '700'],
  styles: ['normal'],
  subsets: ['latin-ext'],
  display: 'swap',
});

export const metadata = {
  title: 'Crud-NextsJS',
  description: 'Generated by Alexander',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">{children}</body>
    </html>
  );
}
